name: Discord Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - env:
          DATA: >
            {
              "embeds": [
                {
                  "title": "5-seny-park-community-fe-react",
                  "description": "새로운 PR이 도착했습니다!\n\nhttps://www.acmicpc.net/problem/1756",
                  "url": "https://github.com/Munbin-Lee/test/pull/1"
                }
              ]
            }
        run: >
          curl -X
          POST -H 'Content-type:application/json'
          -d "$DATA"
          ${{ secrets.DISCORD_WEBHOOK_URL }}

